### ISSUE TITLE
Post the `validate_translaiton` output as a pull request comment

### ISSUE THREAD

**Issue by OmarIthawi** [openedx/openedx-translations#566]
### Description

Add the following to the `validate-translation-files.yml` for better Developer Experience:

```yml
      - name: Validate translation files
        id: validate_translation_files
        run: |
          make validate_translation_files 2>&1 > make_output.txt

      - name: Send failure comment
        if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const makeOutput = fs.readFileSync('make_output.txt', 'utf8');

            const comment = `
            This pull request contains invalid translation files. Please fix the errors and push again.

            <details><summary>Output from `make validate_translation_files`</summary>
            \`\`\`
            ${makeOutput}
            \`\`\`
            </details>

            This comment was posted by the `validate-translation-files.yml` GitHub workflow.
            `;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment,
            });

            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['translations-error'],
            })
```

### Related PR

This is related to #564
